project: SBR_Net_eburhan
entity: cisl-bu

program: main.py
method: grid # random, grid, bayes, hyperband

metric:
  name: avg_train_loss
  goal: minimize

parameters:
  batch_size: 
    value: 9 # [4, 8, 16, 32]
  in_channels_rfv: 
    value: 24
  in_channels_stack:
    value: 9
  num_blocks: 
    value: 20 #[10, 15, 20]

  learning_rate: 
    value: 1e-4 #[1e-6, 1e-5, 1e-4, 1e-3, 1e-2]
  weight_decay: 
    value: 0 # [1e-3, 1e-5, 1e-7]

  T_max:
    value: 100 # [100, 500, 1000]
  eta_min:
    value: 1e-7
  last_epoch:
    value: -1

  num_epochs: 
    value: 10000
  
  quantile:
    value: 0.95

  criterion:
    value: "PinballLoss"

  train_single_sample: 
    value: True # [True, False] # Bool type

  use_mixed_precision: 
    value: False # [True, False] # Bool type