project_name: SBR_Net_eburhan
entity: cisl-bu

progran: main.py
method: random # random, grid, bayes, hyperband

metric:
  name: train_loss
  goal: minimize

parameters:
  batch_size: 9
  in_channels_rfv: 24
  in_channels_stack: 9
  num_blocks: 20

  learning_rate: 
    values: [0.001, 0.01]
  weight_decay: 
    values: [1e-3, 1e-5, 1e-7]

  T_max: 1000
  eta_min: 0
  last_epoch: -1

  num_epochs: 
    values: [30, 50, 100, 150, 200, 250, 300]

train_single_sample: True

use_mixed_precision: False